-- MySQL Script generated by MySQL Workbench
-- Mon Feb 12 20:23:43 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema team34
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `team34` ;

-- -----------------------------------------------------
-- Schema team34
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `team34` DEFAULT CHARACTER SET latin1 ;
SHOW WARNINGS;
USE `team34` ;

-- -----------------------------------------------------
-- Table `team34`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `team34`.`customer` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `team34`.`customer` (
  `id` INT(11) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(11) NULL DEFAULT NULL,
  `password` VARCHAR(45) NOT NULL,
  `score` INT(11) NOT NULL DEFAULT '5',
  `dob` DATETIME NULL DEFAULT NULL,
  `create_date` DATETIME NOT NULL,
  `last_log_in` DATETIME NOT NULL,
  `level` INT(11) NOT NULL DEFAULT '0',
  `privacy_level` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `team34`.`customer_followlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `team34`.`customer_followlist` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `team34`.`customer_followlist` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `customer_from_id` INT(11) NOT NULL,
  `customer_to_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `team34`.`customer_level`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `team34`.`customer_level` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `team34`.`customer_level` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `team34`.`customer_playlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `team34`.`customer_playlist` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `team34`.`customer_playlist` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `customer_id` INT(11) NOT NULL,
  `movie_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `team34`.`customer_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `team34`.`customer_tag` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `team34`.`customer_tag` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `weights` INT(11) NOT NULL,
  `customer_id` INT(11) NOT NULL,
  `tag_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `team34`.`movie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `team34`.`movie` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `team34`.`movie` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `date` DATETIME NOT NULL,
  `score` VARCHAR(45) NOT NULL DEFAULT '0',
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `level` VARCHAR(45) NOT NULL DEFAULT 'PG-13',
  `language` VARCHAR(45) NOT NULL,
  `time` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `team34`.`movie_actor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `team34`.`movie_actor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `team34`.`movie_actor` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `team34`.`movie_comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `team34`.`movie_comment` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `team34`.`movie_comment` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `review` VARCHAR(500) NULL DEFAULT NULL,
  `score` INT(11) NULL DEFAULT NULL,
  `date` DATETIME NOT NULL,
  `customer_id` INT(11) NOT NULL,
  `movie_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `team34`.`movie_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `team34`.`movie_detail` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `team34`.`movie_detail` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `actor_play` VARCHAR(45) NOT NULL,
  `actor_id` VARCHAR(45) NOT NULL,
  `movie_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `team34`.`movie_link`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `team34`.`movie_link` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `team34`.`movie_link` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `movie_id` INT(11) NOT NULL,
  `link` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `team34`.`movie_productor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `team34`.`movie_productor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `team34`.`movie_productor` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `movie_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `team34`.`movie_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `team34`.`movie_tag` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `team34`.`movie_tag` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `weights` INT(11) NOT NULL,
  `movie_id` INT(11) NOT NULL,
  `tag_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `team34`.`movie_trailor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `team34`.`movie_trailor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `team34`.`movie_trailor` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `movie_id` VARCHAR(45) NOT NULL,
  `trailor_website` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `team34`.`system_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `team34`.`system_log` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `team34`.`system_log` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `date` DATETIME NULL DEFAULT NULL,
  `description` VARCHAR(500) NULL DEFAULT NULL,
  `error` TINYINT(4) NULL DEFAULT NULL,
  `usercase` VARCHAR(45) NULL DEFAULT NULL,
  `customer_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `team34`.`tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `team34`.`tag` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `team34`.`tag` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
