-- MySQL Script generated by MySQL Workbench
-- Thu Feb  8 01:32:48 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema team34
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `team34` ;

-- -----------------------------------------------------
-- Schema team34
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `team34` DEFAULT CHARACTER SET latin1 ;
SHOW WARNINGS;
USE `team34` ;

-- -----------------------------------------------------
-- Table `team34`.`movie_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `team34`.`movie_detail` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `team34`.`movie_detail` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `actor_play` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `team34`.`actor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `team34`.`actor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `team34`.`actor` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `actor`
    FOREIGN KEY (`id`)
    REFERENCES `team34`.`movie_detail` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `team34`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `team34`.`comment` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `team34`.`comment` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `review` VARCHAR(500) NULL DEFAULT NULL,
  `score` INT(11) NULL DEFAULT NULL,
  `date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `team34`.`customer_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `team34`.`customer_tag` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `team34`.`customer_tag` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `weights` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `team34`.`followlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `team34`.`followlist` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `team34`.`followlist` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `team34`.`log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `team34`.`log` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `team34`.`log` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `date` DATETIME NULL DEFAULT NULL,
  `description` VARCHAR(500) NULL DEFAULT NULL,
  `error` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `team34`.`playlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `team34`.`playlist` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `team34`.`playlist` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `team34`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `team34`.`customer` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `team34`.`customer` (
  `id` INT(11) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(11) NULL DEFAULT NULL,
  `password` VARCHAR(45) NOT NULL,
  `score` INT(11) NOT NULL DEFAULT '5',
  `dob` DATETIME NULL DEFAULT NULL,
  `create_date` DATETIME NOT NULL,
  `last_log_in` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `customer`
    FOREIGN KEY (`id`)
    REFERENCES `team34`.`comment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `customer_customer_tag`
    FOREIGN KEY (`id`)
    REFERENCES `team34`.`customer_tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `customer_followlist_from`
    FOREIGN KEY (`id`)
    REFERENCES `team34`.`followlist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `customer_followlist_to`
    FOREIGN KEY (`id`)
    REFERENCES `team34`.`followlist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `customer_log`
    FOREIGN KEY (`id`)
    REFERENCES `team34`.`log` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `customer_playlist`
    FOREIGN KEY (`id`)
    REFERENCES `team34`.`playlist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `team34`.`customer` (`id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `team34`.`customer_level`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `team34`.`customer_level` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `team34`.`customer_level` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `level`
    FOREIGN KEY (`id`)
    REFERENCES `team34`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `team34`.`movie_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `team34`.`movie_tag` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `team34`.`movie_tag` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `weights` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `team34`.`movie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `team34`.`movie` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `team34`.`movie` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `date` DATETIME NOT NULL,
  `score` VARCHAR(45) NOT NULL DEFAULT '0',
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `level` VARCHAR(45) NOT NULL DEFAULT 'PG-13',
  `language` VARCHAR(45) NOT NULL,
  `time` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `movie`
    FOREIGN KEY (`id`)
    REFERENCES `team34`.`movie_detail` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `movie_comment`
    FOREIGN KEY (`id`)
    REFERENCES `team34`.`comment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `movie_movie_tag`
    FOREIGN KEY (`id`)
    REFERENCES `team34`.`movie_tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `movie_playlist`
    FOREIGN KEY (`id`)
    REFERENCES `team34`.`playlist` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `team34`.`productor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `team34`.`productor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `team34`.`productor` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `productor`
    FOREIGN KEY (`id`)
    REFERENCES `team34`.`movie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `team34`.`profile_level`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `team34`.`profile_level` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `team34`.`profile_level` (
  `id` INT(11) NOT NULL,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `profile_customer`
    FOREIGN KEY (`id`)
    REFERENCES `team34`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `team34`.`tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `team34`.`tag` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `team34`.`tag` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `tag_customer`
    FOREIGN KEY (`id`)
    REFERENCES `team34`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tag_movie`
    FOREIGN KEY (`id`)
    REFERENCES `team34`.`movie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
